name: Build iOS Tweak

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Theos
      run: |
        # Install dependencies
        sudo apt-get update
        sudo apt-get install -y git curl wget unzip build-essential
        
        # Install Theos
        git clone --recursive https://github.com/theos/theos.git ~/theos
        
        # Install iOS SDKs
        cd /tmp
        wget https://github.com/theos/sdks/archive/refs/heads/master.zip
        unzip master.zip
        sudo cp -r sdks-master/iPhoneOS16.5.sdk ~/theos/sdks/
        sudo chown -R $USER:$USER ~/theos/sdks
        
        # Install toolchain using system clang
        sudo apt-get install -y clang llvm
        mkdir -p ~/theos/toolchain/linux/iphone/bin
        ln -sf /usr/bin/clang ~/theos/toolchain/linux/iphone/bin/clang
        ln -sf /usr/bin/clang++ ~/theos/toolchain/linux/iphone/bin/clang++
        ln -sf /usr/bin/ld ~/theos/toolchain/linux/iphone/bin/ld
        ln -sf /usr/bin/ar ~/theos/toolchain/linux/iphone/bin/ar
        ln -sf /usr/bin/ranlib ~/theos/toolchain/linux/iphone/bin/ranlib
        ln -sf /usr/bin/strip ~/theos/toolchain/linux/iphone/bin/strip
        ln -sf /usr/bin/nm ~/theos/toolchain/linux/iphone/bin/nm
        ln -sf /usr/bin/otool ~/theos/toolchain/linux/iphone/bin/otool
        ln -sf /usr/bin/install_name_tool ~/theos/toolchain/linux/iphone/bin/install_name_tool
        ln -sf /usr/bin/codesign_allocate ~/theos/toolchain/linux/iphone/bin/codesign_allocate
        
        # Set environment variables
        echo "THEOS=~/theos" >> $GITHUB_ENV
        echo "PATH=~/theos/bin:$PATH" >> $GITHUB_ENV
        
    - name: Build tweak
      run: |
        make clean
        make package
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tweak-package
        path: "*.deb"
